requirejs(['text'], function(data){});
requirejs(['json'], function(data){});
requirejs(['../constants/TestConstants'], function(data){});
requirejs(['../constants/Constants'], function(data){});
requirejs(['EventHandlers'], function(data){});
requirejs(["TestCompiler"], function(testcompiler) {});
requirejs(["scripts/FileSaver.min.js"], function(FileSaver) {});
requirejs(["jquery"], function(jQuery) {});
requirejs(["SelectorFilter"], function(SelectorFilter) {});
requirejs(["AssertionsAlertCompiler"], function(Assertions) {});
requirejs(["InputElementHandler"], function(Input) {});
requirejs(["jquery_ui/jquery-ui"], function(jQueryUI) {});